# -*- coding: utf-8 -*-
"""test_your_api_key.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tdxUhyBHGV6ihxIloYhFQiAwHyJqfxIg

# Test your API key

### 1. Copy your API key here.
Your API key contains credits that should allows you to query GPT-5-Nano ~20,000 times (assuming inputs and outputs are both around 500 tokens).

More API quota is available at cost, please ping us on Piazza for instructions of recharging API credits.
"""

# Please paste the API Key sent to you on Piazza here.
API_KEY = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

"""### 2. Set the host URL.
Two host urls are optional:

-Host1: `https://hk-api.gptbest.vip`

-Host2: `https://api.bltcy.ai` (Recommended)
"""

HOST_URL = "https://api.bltcy.ai"

"""### 3. Send "post" request to the server and wait for response."""

import openai

client = openai.OpenAI(
    base_url=f"{HOST_URL}/v1",
    api_key=API_KEY,
    timeout=120,
)

# Send chat request
response = client.chat.completions.create(
    model="gpt-5-nano",
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Hello!"}
    ]
)

# Save response data
data = response.model_dump()
data

"""### 4. Get response content

Run the following cell if procedure 3 runs successfully.
"""

data["choices"][0]["message"]["content"]